# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'net_ass3.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UDP_Server(object):
    def setupUi(self, UDP_Server):
        UDP_Server.setObjectName("UDP_Server")
        UDP_Server.resize(704, 621)
        self.groupBox_link = QtWidgets.QGroupBox(UDP_Server)
        self.groupBox_link.setGeometry(QtCore.QRect(10, 10, 151, 241))
        self.groupBox_link.setObjectName("groupBox_link")
        self.label = QtWidgets.QLabel(self.groupBox_link)
        self.label.setGeometry(QtCore.QRect(70, 20, 54, 12))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_link)
        self.comboBox.setGeometry(QtCore.QRect(28, 40, 91, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox_link)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 54, 12))
        self.label_2.setObjectName("label_2")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.groupBox_link)
        self.lineEdit_ip.setGeometry(QtCore.QRect(10, 100, 113, 20))
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.label_5 = QtWidgets.QLabel(self.groupBox_link)
        self.label_5.setGeometry(QtCore.QRect(70, 140, 54, 12))
        self.label_5.setObjectName("label_5")
        self.lineEdit_port = QtWidgets.QLineEdit(self.groupBox_link)
        self.lineEdit_port.setGeometry(QtCore.QRect(10, 160, 113, 20))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.pushButton_link = QtWidgets.QPushButton(self.groupBox_link)
        self.pushButton_link.setGeometry(QtCore.QRect(50, 200, 75, 23))
        self.pushButton_link.setObjectName("pushButton_link")
        self.groupBox_rec = QtWidgets.QGroupBox(UDP_Server)
        self.groupBox_rec.setGeometry(QtCore.QRect(10, 330, 131, 61))
        self.groupBox_rec.setObjectName("groupBox_rec")
        self.splitter = QtWidgets.QSplitter(self.groupBox_rec)
        self.splitter.setGeometry(QtCore.QRect(10, 20, 116, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.checkBox_hex = QtWidgets.QCheckBox(self.splitter)
        self.checkBox_hex.setObjectName("checkBox_hex")
        self.pushButton_clear = QtWidgets.QPushButton(self.splitter)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.tabWidget = QtWidgets.QTabWidget(UDP_Server)
        self.tabWidget.setGeometry(QtCore.QRect(170, 10, 521, 381))
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.groupBox_para1 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        self.groupBox_para1.setGeometry(QtCore.QRect(10, 100, 501, 81))
        self.groupBox_para1.setObjectName("groupBox_para1")
        self.lineEdit_reset_time = QtWidgets.QLineEdit(self.groupBox_para1)
        self.lineEdit_reset_time.setGeometry(QtCore.QRect(350, 20, 61, 23))
        self.lineEdit_reset_time.setObjectName("lineEdit_reset_time")
        self.label_13 = QtWidgets.QLabel(self.groupBox_para1)
        self.label_13.setGeometry(QtCore.QRect(11, 20, 81, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_para1)
        self.label_14.setGeometry(QtCore.QRect(270, 20, 81, 16))
        self.label_14.setObjectName("label_14")
        self.pushButton_para1_get = QtWidgets.QPushButton(self.groupBox_para1)
        self.pushButton_para1_get.setGeometry(QtCore.QRect(420, 20, 75, 23))
        self.pushButton_para1_get.setObjectName("pushButton_para1_get")
        self.lineEdit_heart = QtWidgets.QLineEdit(self.groupBox_para1)
        self.lineEdit_heart.setGeometry(QtCore.QRect(90, 20, 41, 23))
        self.lineEdit_heart.setObjectName("lineEdit_heart")
        self.lineEdit_sleep = QtWidgets.QLineEdit(self.groupBox_para1)
        self.lineEdit_sleep.setGeometry(QtCore.QRect(220, 20, 41, 23))
        self.lineEdit_sleep.setObjectName("lineEdit_sleep")
        self.label_15 = QtWidgets.QLabel(self.groupBox_para1)
        self.label_15.setGeometry(QtCore.QRect(140, 20, 81, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_verify_code = QtWidgets.QLineEdit(self.groupBox_para1)
        self.lineEdit_verify_code.setGeometry(QtCore.QRect(350, 50, 61, 23))
        self.lineEdit_verify_code.setObjectName("lineEdit_verify_code")
        self.label_16 = QtWidgets.QLabel(self.groupBox_para1)
        self.label_16.setGeometry(QtCore.QRect(270, 50, 54, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_online = QtWidgets.QLineEdit(self.groupBox_para1)
        self.lineEdit_online.setGeometry(QtCore.QRect(220, 50, 41, 23))
        self.lineEdit_online.setObjectName("lineEdit_online")
        self.label_17 = QtWidgets.QLabel(self.groupBox_para1)
        self.label_17.setGeometry(QtCore.QRect(140, 50, 81, 16))
        self.label_17.setObjectName("label_17")
        self.pushButton_para1_set = QtWidgets.QPushButton(self.groupBox_para1)
        self.pushButton_para1_set.setGeometry(QtCore.QRect(420, 50, 75, 23))
        self.pushButton_para1_set.setObjectName("pushButton_para1_set")
        self.label_18 = QtWidgets.QLabel(self.groupBox_para1)
        self.label_18.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_18.setObjectName("label_18")
        self.lineEdit_sample = QtWidgets.QLineEdit(self.groupBox_para1)
        self.lineEdit_sample.setGeometry(QtCore.QRect(90, 50, 41, 23))
        self.lineEdit_sample.setObjectName("lineEdit_sample")
        self.groupBox_para2 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        self.groupBox_para2.setGeometry(QtCore.QRect(10, 190, 501, 81))
        self.groupBox_para2.setObjectName("groupBox_para2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_para2)
        self.label_10.setGeometry(QtCore.QRect(60, 20, 21, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_ip2 = QtWidgets.QLineEdit(self.groupBox_para2)
        self.lineEdit_ip2.setGeometry(QtCore.QRect(90, 20, 123, 23))
        self.lineEdit_ip2.setObjectName("lineEdit_ip2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_para2)
        self.label_11.setGeometry(QtCore.QRect(230, 20, 31, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_port2 = QtWidgets.QLineEdit(self.groupBox_para2)
        self.lineEdit_port2.setGeometry(QtCore.QRect(260, 20, 121, 23))
        self.lineEdit_port2.setObjectName("lineEdit_port2")
        self.pushButton_para2_get = QtWidgets.QPushButton(self.groupBox_para2)
        self.pushButton_para2_get.setGeometry(QtCore.QRect(420, 20, 75, 23))
        self.pushButton_para2_get.setObjectName("pushButton_para2_get")
        self.label_12 = QtWidgets.QLabel(self.groupBox_para2)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_12.setObjectName("label_12")
        self.pushButton_para2_set = QtWidgets.QPushButton(self.groupBox_para2)
        self.pushButton_para2_set.setGeometry(QtCore.QRect(420, 50, 75, 23))
        self.pushButton_para2_set.setObjectName("pushButton_para2_set")
        self.lineEdit_phone_number = QtWidgets.QLineEdit(self.groupBox_para2)
        self.lineEdit_phone_number.setGeometry(QtCore.QRect(90, 50, 311, 23))
        self.lineEdit_phone_number.setObjectName("lineEdit_phone_number")
        self.groupBox_para3 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        self.groupBox_para3.setGeometry(QtCore.QRect(10, 280, 501, 81))
        self.groupBox_para3.setObjectName("groupBox_para3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_para3)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_freq = QtWidgets.QLineEdit(self.groupBox_para3)
        self.lineEdit_freq.setGeometry(QtCore.QRect(91, 20, 101, 23))
        self.lineEdit_freq.setObjectName("lineEdit_freq")
        self.label_7 = QtWidgets.QLabel(self.groupBox_para3)
        self.label_7.setGeometry(QtCore.QRect(210, 20, 81, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_limit_rate = QtWidgets.QLineEdit(self.groupBox_para3)
        self.lineEdit_limit_rate.setGeometry(QtCore.QRect(292, 20, 101, 23))
        self.lineEdit_limit_rate.setObjectName("lineEdit_limit_rate")
        self.pushButton_para3_get = QtWidgets.QPushButton(self.groupBox_para3)
        self.pushButton_para3_get.setGeometry(QtCore.QRect(420, 20, 75, 23))
        self.pushButton_para3_get.setObjectName("pushButton_para3_get")
        self.pushButton_para3_set = QtWidgets.QPushButton(self.groupBox_para3)
        self.pushButton_para3_set.setGeometry(QtCore.QRect(420, 50, 75, 23))
        self.pushButton_para3_set.setObjectName("pushButton_para3_set")
        self.label_8 = QtWidgets.QLabel(self.groupBox_para3)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_wave = QtWidgets.QLineEdit(self.groupBox_para3)
        self.lineEdit_wave.setGeometry(QtCore.QRect(91, 50, 101, 23))
        self.lineEdit_wave.setObjectName("lineEdit_wave")
        self.lineEdit_reserve = QtWidgets.QLineEdit(self.groupBox_para3)
        self.lineEdit_reserve.setGeometry(QtCore.QRect(292, 50, 101, 23))
        self.lineEdit_reserve.setObjectName("lineEdit_reserve")
        self.label_9 = QtWidgets.QLabel(self.groupBox_para3)
        self.label_9.setGeometry(QtCore.QRect(250, 50, 31, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton_connect = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_connect.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.pushButton_syn = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_syn.setGeometry(QtCore.QRect(110, 10, 75, 23))
        self.pushButton_syn.setObjectName("pushButton_syn")
        self.pushButton_get_time = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_get_time.setGeometry(QtCore.QRect(210, 10, 75, 23))
        self.pushButton_get_time.setObjectName("pushButton_get_time")
        self.pushButton_condition = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_condition.setGeometry(QtCore.QRect(320, 10, 75, 23))
        self.pushButton_condition.setObjectName("pushButton_condition")
        self.pushButton_reset = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_reset.setGeometry(QtCore.QRect(430, 10, 75, 23))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.groupBox_password = QtWidgets.QGroupBox(self.tabWidgetPage1)
        self.groupBox_password.setGeometry(QtCore.QRect(10, 40, 501, 51))
        self.groupBox_password.setObjectName("groupBox_password")
        self.label_3 = QtWidgets.QLabel(self.groupBox_password)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 36, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_password_old = QtWidgets.QLineEdit(self.groupBox_password)
        self.lineEdit_password_old.setGeometry(QtCore.QRect(60, 20, 122, 23))
        self.lineEdit_password_old.setObjectName("lineEdit_password_old")
        self.lineEdit_password_new = QtWidgets.QLineEdit(self.groupBox_password)
        self.lineEdit_password_new.setGeometry(QtCore.QRect(231, 20, 122, 23))
        self.lineEdit_password_new.setObjectName("lineEdit_password_new")
        self.label_4 = QtWidgets.QLabel(self.groupBox_password)
        self.label_4.setGeometry(QtCore.QRect(189, 20, 36, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_set_password = QtWidgets.QPushButton(self.groupBox_password)
        self.pushButton_set_password.setGeometry(QtCore.QRect(420, 20, 75, 23))
        self.pushButton_set_password.setObjectName("pushButton_set_password")
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.groupBox_freq = QtWidgets.QGroupBox(self.tabWidgetPage2)
        self.groupBox_freq.setGeometry(QtCore.QRect(10, 10, 501, 61))
        self.groupBox_freq.setObjectName("groupBox_freq")
        self.pushButton_freq = QtWidgets.QPushButton(self.groupBox_freq)
        self.pushButton_freq.setGeometry(QtCore.QRect(420, 20, 75, 23))
        self.pushButton_freq.setObjectName("pushButton_freq")
        self.graphicsView = GraphicsLayoutWidget(self.tabWidgetPage2)
        self.graphicsView.setGeometry(QtCore.QRect(10, 80, 501, 271))
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tabWidgetPage3 = QtWidgets.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")
        self.groupBox_wave = QtWidgets.QGroupBox(self.tabWidgetPage3)
        self.groupBox_wave.setGeometry(QtCore.QRect(10, 10, 501, 61))
        self.groupBox_wave.setObjectName("groupBox_wave")
        self.pushButton_wave = QtWidgets.QPushButton(self.groupBox_wave)
        self.pushButton_wave.setGeometry(QtCore.QRect(420, 20, 75, 23))
        self.pushButton_wave.setObjectName("pushButton_wave")
        self.graphicsView_2 = GraphicsLayoutWidget(self.tabWidgetPage3)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 80, 501, 271))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.tabWidget.addTab(self.tabWidgetPage3, "")
        self.textBrowser = QtWidgets.QTextBrowser(UDP_Server)
        self.textBrowser.setGeometry(QtCore.QRect(10, 400, 681, 211))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_remote_ip = QtWidgets.QGroupBox(UDP_Server)
        self.groupBox_remote_ip.setGeometry(QtCore.QRect(10, 260, 151, 61))
        self.groupBox_remote_ip.setObjectName("groupBox_remote_ip")
        self.lineEdit_remote_ip = QtWidgets.QLineEdit(self.groupBox_remote_ip)
        self.lineEdit_remote_ip.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.lineEdit_remote_ip.setObjectName("lineEdit_remote_ip")

        self.retranslateUi(UDP_Server)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(UDP_Server)

    def retranslateUi(self, UDP_Server):
        _translate = QtCore.QCoreApplication.translate
        UDP_Server.setWindowTitle(_translate("UDP_Server", "Form"))
        self.groupBox_link.setTitle(_translate("UDP_Server", "网络设置"))
        self.label.setText(_translate("UDP_Server", "协议类型"))
        self.comboBox.setItemText(0, _translate("UDP_Server", "UDP server"))
        self.comboBox.setItemText(1, _translate("UDP_Server", "UDP client"))
        self.comboBox.setItemText(2, _translate("UDP_Server", "TCP server"))
        self.comboBox.setItemText(3, _translate("UDP_Server", "TCP client"))
        self.label_2.setText(_translate("UDP_Server", "本地IP"))
        self.label_5.setText(_translate("UDP_Server", "本地端口"))
        self.pushButton_link.setText(_translate("UDP_Server", "连接"))
        self.groupBox_rec.setTitle(_translate("UDP_Server", "显示区"))
        self.checkBox_hex.setText(_translate("UDP_Server", "Hex"))
        self.pushButton_clear.setText(_translate("UDP_Server", "清空"))
        self.groupBox_para1.setTitle(_translate("UDP_Server", "运行参数"))
        self.label_13.setText(_translate("UDP_Server", "心跳间隔(min)"))
        self.label_14.setText(_translate("UDP_Server", "重启时间(dhm)"))
        self.pushButton_para1_get.setText(_translate("UDP_Server", "获取"))
        self.label_15.setText(_translate("UDP_Server", "休眠时长(min)"))
        self.label_16.setText(_translate("UDP_Server", "密文认证"))
        self.label_17.setText(_translate("UDP_Server", "在线时长(min)"))
        self.pushButton_para1_set.setText(_translate("UDP_Server", "设置"))
        self.label_18.setText(_translate("UDP_Server", "采样间隔(min)"))
        self.groupBox_para2.setTitle(_translate("UDP_Server", "网络参数"))
        self.label_10.setText(_translate("UDP_Server", "IP"))
        self.label_11.setText(_translate("UDP_Server", "port"))
        self.pushButton_para2_get.setText(_translate("UDP_Server", "获取"))
        self.label_12.setText(_translate("UDP_Server", "phone number"))
        self.pushButton_para2_set.setText(_translate("UDP_Server", "设置"))
        self.groupBox_para3.setTitle(_translate("UDP_Server", "故障参数"))
        self.label_6.setText(_translate("UDP_Server", "工频阈值(A)"))
        self.label_7.setText(_translate("UDP_Server", "阈值百分数(%)"))
        self.pushButton_para3_get.setText(_translate("UDP_Server", "获取"))
        self.pushButton_para3_set.setText(_translate("UDP_Server", "设置"))
        self.label_8.setText(_translate("UDP_Server", "行波阈值(A)"))
        self.label_9.setText(_translate("UDP_Server", "预留"))
        self.pushButton_connect.setText(_translate("UDP_Server", "开机联络"))
        self.pushButton_syn.setText(_translate("UDP_Server", "校时"))
        self.pushButton_get_time.setText(_translate("UDP_Server", "查询时间"))
        self.pushButton_condition.setText(_translate("UDP_Server", "工况"))
        self.pushButton_reset.setText(_translate("UDP_Server", "复位"))
        self.groupBox_password.setTitle(_translate("UDP_Server", "更改密码"))
        self.label_3.setText(_translate("UDP_Server", "旧密码"))
        self.label_4.setText(_translate("UDP_Server", "新密码"))
        self.pushButton_set_password.setText(_translate("UDP_Server", "设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("UDP_Server", "参数"))
        self.groupBox_freq.setTitle(_translate("UDP_Server", "获取工频"))
        self.pushButton_freq.setText(_translate("UDP_Server", "获取工频"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("UDP_Server", "工频"))
        self.groupBox_wave.setTitle(_translate("UDP_Server", "获取行波"))
        self.pushButton_wave.setText(_translate("UDP_Server", "获取行波"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("UDP_Server", "行波"))
        self.groupBox_remote_ip.setTitle(_translate("UDP_Server", "远方ip"))

from pyqtgraph import GraphicsLayoutWidget